// Environmental Interaction Module (Phase 4)
//
// From COMPREHENSIVE_REFACTOR_PLAN.md Phase 4:
// "Add Environmental Interaction - Entities interact with their environment,
// Environment affects entity evolution, Entity actions affect environment"
//
// This module implements:
// 1. Environmental state (energy fields, matter density, vibrational fields)
// 2. Entity-environment interaction (bidirectional)
// 3. Environmental evolution over time
// 4. Environmental influence on entity evolution

use crate::entity_layer7::layer7::{DensityLevel, EntityId, SubSubLogos};
use crate::matter::Coordinate3D;
use crate::types::Float;
use std::collections::HashMap;

/// Helper function to convert Coordinate3D to a string key
fn coordinate_to_key(coord: &Coordinate3D) -> String {
    format!("{:.6}_{:.6}_{:.6}", coord.x, coord.y, coord.z)
}

// ============================================================================
// ENVIRONMENTAL STATE
// ============================================================================

/// Environmental State
///
/// Represents the state of the environment at a given location.
/// The environment consists of energy fields, matter density, and vibrational fields.
#[derive(Debug, Clone)]
pub struct EnvironmentalState {
    /// Energy fields at different locations (using string keys)
    pub energy_fields: HashMap<String, EnergyField>,

    /// Matter density at different locations (using string keys)
    pub matter_density: HashMap<String, Float>,

    /// Vibrational field at different locations (using string keys)
    pub vibrational_fields: HashMap<String, VibrationalField>,

    /// Collective fields (for collective entities)
    pub collective_fields: HashMap<EntityId, CollectiveField>,

    /// Environmental coherence (0.0 to 1.0)
    pub environmental_coherence: Float,

    /// Environmental resonance frequency
    pub environmental_resonance: Float,
}

/// Energy Field
///
/// Represents an energy field at a specific location.
#[derive(Debug, Clone)]
pub struct EnergyField {
    /// Field location
    pub location: Coordinate3D,

    /// Energy intensity (0.0 to 1.0)
    pub intensity: Float,

    /// Field type
    pub field_type: EnergyFieldType,

    /// Field coherence (0.0 to 1.0)
    pub coherence: Float,
}

/// Type of energy field
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EnergyFieldType {
    /// Intelligent Infinity energy (unconditional love)
    IntelligentInfinity,

    /// Light/Love energy (creative energy)
    LightLove,

    /// Logos energy (structuring energy)
    Logos,

    /// Archetypical energy (pattern energy)
    Archetypical,

    /// Catalyst energy (transformative energy)
    Catalyst,
}

/// Vibrational Field
///
/// Represents the vibrational state at a specific location.
#[derive(Debug, Clone)]
pub struct VibrationalField {
    /// Field location
    pub location: Coordinate3D,

    /// Vibrational frequency (0.0 to 1.0)
    pub frequency: Float,

    /// Vibrational coherence (0.0 to 1.0)
    pub coherence: Float,

    /// Vibrational phase (0.0 to 2π)
    pub phase: Float,
}

/// Collective Field
///
/// Represents the collective field generated by a collective entity.
#[derive(Debug, Clone)]
pub struct CollectiveField {
    /// Collective entity ID
    pub collective_id: EntityId,

    /// Field strength (0.0 to 1.0)
    pub strength: Float,

    /// Field coherence (0.0 to 1.0)
    pub coherence: Float,

    /// Field influence radius
    pub influence_radius: Float,

    /// Member entities contributing to this field
    pub contributing_entities: Vec<EntityId>,
}

/// Environmental Effect
///
/// Represents the effect of environment on an entity (or entity on environment).
#[derive(Debug, Clone)]
pub struct EnvironmentalEffect {
    /// Energy field effect
    pub energy_effect: Float,

    /// Matter density effect
    pub matter_effect: Float,

    /// Vibrational field effect
    pub vibrational_effect: Float,

    /// Overall magnitude of effect (0.0 to 1.0)
    pub magnitude: Float,

    /// Effect type (influence from environment or influence to environment)
    pub effect_type: EnvironmentalEffectType,
}

/// Type of environmental effect
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EnvironmentalEffectType {
    /// Environment affecting entity
    EnvironmentToEntity,

    /// Entity affecting environment
    EntityToEnvironment,

    /// Bidirectional influence
    Bidirectional,
}

// ============================================================================
// ENVIRONMENTAL INTERACTION MANAGER
// ============================================================================

/// Environmental Interaction Manager
///
/// Manages environmental state and entity-environment interactions.
pub struct EnvironmentalInteractionManager {
    /// Current environmental state
    pub environment: EnvironmentalState,

    /// Simulation time
    pub simulation_time: u64,

    /// Statistics
    pub statistics: EnvironmentalStatistics,
}

/// Environmental Statistics
#[derive(Debug, Clone, Default)]
pub struct EnvironmentalStatistics {
    /// Total energy in environment
    pub total_energy: Float,

    /// Average matter density
    pub average_matter_density: Float,

    /// Average vibrational frequency
    pub average_vibrational_frequency: Float,

    /// Environmental coherence
    pub environmental_coherence: Float,

    /// Number of energy fields
    pub energy_field_count: usize,

    /// Number of collective fields
    pub collective_field_count: usize,

    /// Total entity-environment interactions
    pub total_interactions: usize,

    /// Average interaction magnitude
    pub average_interaction_magnitude: Float,
}

impl EnvironmentalInteractionManager {
    /// Create a new environmental interaction manager
    pub fn new() -> Self {
        EnvironmentalInteractionManager {
            environment: EnvironmentalState::new(),
            simulation_time: 0,
            statistics: EnvironmentalStatistics::default(),
        }
    }

    /// Initialize environment based on entities
    pub fn initialize_environment(&mut self, entities: &HashMap<EntityId, SubSubLogos>) {
        // Create energy fields at entity locations
        for entity in entities.values() {
            if let Some(physical) = &entity.physical_entity {
                let location = match physical {
                    crate::matter::Matter::Particle(p) => p.position,
                    crate::matter::Matter::Atom(a) => a.position,
                    crate::matter::Matter::Molecule(m) => {
                        // Use position of first atom
                        m.atoms
                            .first()
                            .map(|a| a.position)
                            .unwrap_or(Coordinate3D::origin())
                    }
                    crate::matter::Matter::Cell(_) => Coordinate3D::origin(), // Cells have no position
                    crate::matter::Matter::Empty => Coordinate3D::origin(),
                };

                // Create energy field
                let energy_field = EnergyField {
                    location,
                    intensity: entity.current_state.consciousness_level,
                    field_type: Self::determine_field_type(entity),
                    coherence: entity.current_state.vibrational_state.coherence,
                };

                let location_key = coordinate_to_key(&location);
                self.environment
                    .energy_fields
                    .insert(location_key.clone(), energy_field);

                // Create vibrational field
                let vibrational_field = VibrationalField {
                    location,
                    frequency: entity.current_state.vibrational_state.frequency,
                    coherence: entity.current_state.vibrational_state.coherence,
                    phase: 0.0,
                };

                self.environment
                    .vibrational_fields
                    .insert(location_key.clone(), vibrational_field);

                // Set matter density based on entity density level
                let matter_density = Self::calculate_matter_density(entity);
                self.environment
                    .matter_density
                    .insert(location_key, matter_density);
            }
        }

        // Create collective fields for collective entities
        for entity in entities.values() {
            if entity.entity_type == crate::entity_layer7::layer7::EntityType::Collective {
                let collective_field = CollectiveField {
                    collective_id: entity.entity_id.clone(),
                    strength: entity.current_state.consciousness_level,
                    coherence: entity.current_state.vibrational_state.coherence,
                    influence_radius: 10.0 * (entity.current_state.consciousness_level + 1.0),
                    contributing_entities: entity.children.clone(),
                };

                self.environment
                    .collective_fields
                    .insert(entity.entity_id.clone(), collective_field);
            }
        }

        // Update environmental coherence
        self.update_environmental_coherence();

        // Update statistics
        self.update_statistics();
    }

    /// Determine energy field type based on entity
    fn determine_field_type(entity: &SubSubLogos) -> EnergyFieldType {
        match entity.evolutionary_attractor.current_density {
            DensityLevel::First => EnergyFieldType::IntelligentInfinity,
            DensityLevel::Second => EnergyFieldType::LightLove,
            DensityLevel::Third => EnergyFieldType::Logos,
            DensityLevel::Fourth => EnergyFieldType::Archetypical,
            DensityLevel::Fifth
            | DensityLevel::Sixth
            | DensityLevel::Seventh
            | DensityLevel::Eighth => EnergyFieldType::Catalyst,
        }
    }

    /// Calculate matter density based on entity
    fn calculate_matter_density(entity: &SubSubLogos) -> Float {
        match entity.evolutionary_attractor.current_density {
            DensityLevel::First => 0.2,  // Low density for 1st density
            DensityLevel::Second => 0.5, // Medium density for 2nd density
            DensityLevel::Third => 0.8,  // High density for 3rd density
            DensityLevel::Fourth => 0.6, // Medium-high for 4th density
            DensityLevel::Fifth
            | DensityLevel::Sixth
            | DensityLevel::Seventh
            | DensityLevel::Eighth => 0.4,
        }
    }

    /// Update environment for one step
    pub fn update_environment(&mut self, entities: &HashMap<EntityId, SubSubLogos>) {
        self.simulation_time += 1;

        // Update energy fields
        self.update_energy_fields(entities);

        // Update vibrational fields
        self.update_vibrational_fields(entities);

        // Update matter density
        self.update_matter_density(entities);

        // Update collective fields
        self.update_collective_fields(entities);

        // Update environmental coherence
        self.update_environmental_coherence();

        // Update statistics
        self.update_statistics();
    }

    /// Update energy fields
    fn update_energy_fields(&mut self, entities: &HashMap<EntityId, SubSubLogos>) {
        for entity in entities.values() {
            if let Some(physical) = &entity.physical_entity {
                let location = match physical {
                    crate::matter::Matter::Particle(p) => p.position,
                    crate::matter::Matter::Atom(a) => a.position,
                    crate::matter::Matter::Molecule(m) => m
                        .atoms
                        .first()
                        .map(|a| a.position)
                        .unwrap_or(Coordinate3D::origin()),
                    crate::matter::Matter::Cell(_) => Coordinate3D::origin(),
                    crate::matter::Matter::Empty => Coordinate3D::origin(),
                };

                let location_key = coordinate_to_key(&location);
                if let Some(field) = self.environment.energy_fields.get_mut(&location_key) {
                    // Update intensity based on entity evolution
                    field.intensity = (field.intensity
                        + entity.current_state.consciousness_level * 0.01)
                        .clamp(0.0, 1.0);

                    // Update coherence based on entity coherence
                    field.coherence = (field.coherence
                        + entity.current_state.vibrational_state.coherence * 0.01)
                        .clamp(0.0, 1.0);
                }
            }
        }
    }

    /// Update vibrational fields
    fn update_vibrational_fields(&mut self, entities: &HashMap<EntityId, SubSubLogos>) {
        for entity in entities.values() {
            if let Some(physical) = &entity.physical_entity {
                let location = match physical {
                    crate::matter::Matter::Particle(p) => p.position,
                    crate::matter::Matter::Atom(a) => a.position,
                    crate::matter::Matter::Molecule(m) => m
                        .atoms
                        .first()
                        .map(|a| a.position)
                        .unwrap_or(Coordinate3D::origin()),
                    crate::matter::Matter::Cell(_) => Coordinate3D::origin(),
                    crate::matter::Matter::Empty => Coordinate3D::origin(),
                };

                let location_key = coordinate_to_key(&location);
                if let Some(field) = self.environment.vibrational_fields.get_mut(&location_key) {
                    // Update frequency based on entity vibrational state
                    field.frequency = entity.current_state.vibrational_state.frequency;

                    // Update coherence based on entity coherence
                    field.coherence = entity.current_state.vibrational_state.coherence;

                    // Update phase (oscillate over time)
                    field.phase = (field.phase + 0.1) % (2.0 * std::f64::consts::PI);
                }
            }
        }
    }

    /// Update matter density
    fn update_matter_density(&mut self, entities: &HashMap<EntityId, SubSubLogos>) {
        for entity in entities.values() {
            if let Some(physical) = &entity.physical_entity {
                let location = match physical {
                    crate::matter::Matter::Particle(p) => p.position,
                    crate::matter::Matter::Atom(a) => a.position,
                    crate::matter::Matter::Molecule(m) => m
                        .atoms
                        .first()
                        .map(|a| a.position)
                        .unwrap_or(Coordinate3D::origin()),
                    crate::matter::Matter::Cell(_) => Coordinate3D::origin(),
                    crate::matter::Matter::Empty => Coordinate3D::origin(),
                };

                // Matter density slowly increases over time as entities evolve
                let new_density = Self::calculate_matter_density(entity);
                let location_key = coordinate_to_key(&location);
                self.environment
                    .matter_density
                    .insert(location_key, new_density);
            }
        }
    }

    /// Update collective fields
    fn update_collective_fields(&mut self, entities: &HashMap<EntityId, SubSubLogos>) {
        for entity in entities.values() {
            if entity.entity_type == crate::entity_layer7::layer7::EntityType::Collective {
                if let Some(field) = self
                    .environment
                    .collective_fields
                    .get_mut(&entity.entity_id)
                {
                    // Update strength based on collective consciousness
                    field.strength = (field.strength
                        + entity.current_state.consciousness_level * 0.01)
                        .clamp(0.0, 1.0);

                    // Update coherence based on collective coherence
                    field.coherence = (field.coherence
                        + entity.current_state.vibrational_state.coherence * 0.01)
                        .clamp(0.0, 1.0);

                    // Update influence radius
                    field.influence_radius =
                        10.0 * (entity.current_state.consciousness_level + 1.0);
                }
            }
        }
    }

    /// Update environmental coherence
    fn update_environmental_coherence(&mut self) {
        if self.environment.vibrational_fields.is_empty() {
            self.environment.environmental_coherence = 0.0;
            return;
        }

        // Calculate average coherence of all vibrational fields
        let total_coherence: Float = self
            .environment
            .vibrational_fields
            .values()
            .map(|f| f.coherence)
            .sum();

        self.environment.environmental_coherence =
            total_coherence / self.environment.vibrational_fields.len() as Float;

        // Calculate environmental resonance frequency
        let total_frequency: Float = self
            .environment
            .vibrational_fields
            .values()
            .map(|f| f.frequency)
            .sum();

        self.environment.environmental_resonance =
            total_frequency / self.environment.vibrational_fields.len() as Float;
    }

    /// Interact with environment
    ///
    /// Entity interacts with environment, and environment interacts with entity.
    /// Returns the net environmental effect on the entity.
    pub fn interact_with_environment(
        &mut self,
        _entity_id: &EntityId,
        entity: &SubSubLogos,
    ) -> EnvironmentalEffect {
        // Find entity location
        let location = if let Some(physical) = &entity.physical_entity {
            match physical {
                crate::matter::Matter::Particle(p) => p.position,
                crate::matter::Matter::Atom(a) => a.position,
                crate::matter::Matter::Molecule(m) => m
                    .atoms
                    .first()
                    .map(|a| a.position)
                    .unwrap_or(Coordinate3D::origin()),
                crate::matter::Matter::Cell(_) => Coordinate3D::origin(),
                crate::matter::Matter::Empty => Coordinate3D::origin(),
            }
        } else {
            Coordinate3D::origin()
        };

        // Get environmental factors
        let energy_effect = self.get_energy_field_effect(&location, entity);
        let matter_effect = self.get_matter_density_effect(&location, entity);
        let vibrational_effect = self.get_vibrational_field_effect(&location, entity);

        // Calculate overall magnitude
        let magnitude =
            (energy_effect.abs() + matter_effect.abs() + vibrational_effect.abs()) / 3.0;

        // Apply entity's influence on environment
        self.apply_entity_influence(&location, entity);

        let effect = EnvironmentalEffect {
            energy_effect,
            matter_effect,
            vibrational_effect,
            magnitude,
            effect_type: EnvironmentalEffectType::Bidirectional,
        };

        // Update statistics
        self.statistics.total_interactions += 1;
        self.statistics.average_interaction_magnitude =
            (self.statistics.average_interaction_magnitude
                * (self.statistics.total_interactions - 1) as Float
                + magnitude)
                / self.statistics.total_interactions as Float;

        effect
    }

    /// Get energy field effect at location
    fn get_energy_field_effect(&self, location: &Coordinate3D, entity: &SubSubLogos) -> Float {
        let location_key = coordinate_to_key(location);
        if let Some(field) = self.environment.energy_fields.get(&location_key) {
            // Energy field effect is based on field intensity and entity sensitivity
            let sensitivity = entity.current_state.consciousness_level;
            field.intensity * sensitivity * 0.1
        } else {
            0.0
        }
    }

    /// Get matter density effect at location
    fn get_matter_density_effect(&self, location: &Coordinate3D, entity: &SubSubLogos) -> Float {
        let location_key = coordinate_to_key(location);
        if let Some(density) = self.environment.matter_density.get(&location_key) {
            // Matter density effect is based on density and entity's current density
            let entity_density_level = match entity.evolutionary_attractor.current_density {
                DensityLevel::First => 0.0,
                DensityLevel::Second => 0.5,
                DensityLevel::Third => 1.0,
                DensityLevel::Fourth
                | DensityLevel::Fifth
                | DensityLevel::Sixth
                | DensityLevel::Seventh
                | DensityLevel::Eighth => 0.8,
            };

            // Higher matter density affects entities with lower density levels more
            (density - entity_density_level).abs() * 0.05
        } else {
            0.0
        }
    }

    /// Get vibrational field effect at location
    fn get_vibrational_field_effect(&self, location: &Coordinate3D, entity: &SubSubLogos) -> Float {
        let location_key = coordinate_to_key(location);
        if let Some(field) = self.environment.vibrational_fields.get(&location_key) {
            // Vibrational field effect is based on frequency match
            let entity_frequency = entity.current_state.vibrational_state.frequency;
            let frequency_diff = (field.frequency - entity_frequency).abs();

            // Closer frequencies = stronger effect
            (1.0 - frequency_diff) * field.coherence * 0.1
        } else {
            0.0
        }
    }

    /// Apply entity's influence on environment
    fn apply_entity_influence(&mut self, location: &Coordinate3D, entity: &SubSubLogos) {
        // Entity influences energy field
        let location_key = coordinate_to_key(location);
        if let Some(field) = self.environment.energy_fields.get_mut(&location_key) {
            // Entity's consciousness level influences field intensity
            field.intensity = (field.intensity + entity.current_state.consciousness_level * 0.005)
                .clamp(0.0, 1.0);
        }

        // Entity influences vibrational field
        let location_key = coordinate_to_key(location);
        if let Some(field) = self.environment.vibrational_fields.get_mut(&location_key) {
            // Entity's vibrational state influences field frequency
            field.frequency = (field.frequency
                + entity.current_state.vibrational_state.frequency * 0.005)
                .clamp(0.0, 1.0);
        }
    }

    /// Update statistics
    fn update_statistics(&mut self) {
        // Calculate total energy
        self.statistics.total_energy = self
            .environment
            .energy_fields
            .values()
            .map(|f| f.intensity)
            .sum();

        // Calculate average matter density
        if !self.environment.matter_density.is_empty() {
            let total_density: Float = self.environment.matter_density.values().sum();
            self.statistics.average_matter_density =
                total_density / self.environment.matter_density.len() as Float;
        }

        // Calculate average vibrational frequency
        if !self.environment.vibrational_fields.is_empty() {
            let total_frequency: Float = self
                .environment
                .vibrational_fields
                .values()
                .map(|f| f.frequency)
                .sum();
            self.statistics.average_vibrational_frequency =
                total_frequency / self.environment.vibrational_fields.len() as Float;
        }

        // Update environmental coherence
        self.statistics.environmental_coherence = self.environment.environmental_coherence;

        // Update field counts
        self.statistics.energy_field_count = self.environment.energy_fields.len();
        self.statistics.collective_field_count = self.environment.collective_fields.len();
    }

    /// Get statistics
    pub fn get_statistics(&self) -> &EnvironmentalStatistics {
        &self.statistics
    }

    /// Get environmental state
    pub fn get_environment(&self) -> &EnvironmentalState {
        &self.environment
    }
}

impl EnvironmentalState {
    /// Create a new environmental state
    pub fn new() -> Self {
        EnvironmentalState {
            energy_fields: HashMap::new(),
            matter_density: HashMap::new(),
            vibrational_fields: HashMap::new(),
            collective_fields: HashMap::new(),
            environmental_coherence: 0.0,
            environmental_resonance: 0.0,
        }
    }
}

impl Default for EnvironmentalInteractionManager {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity_layer7::layer7::{IndividualSpectrumConfiguration, SubSubLogos};
    use crate::foundation::{BlueRealm, GreenRealm, IndigoRealm, VioletRealm};
    use crate::spectrum::{OrangeRealm, RedRealm, SpectrumRatio, SpectrumSide, YellowRealm};

    /// Create a test entity
    fn create_test_entity(id: &str) -> SubSubLogos {
        let violet = VioletRealm::new();
        let indigo = IndigoRealm::new();
        let blue = BlueRealm::new();
        let green = GreenRealm::new();
        let yellow = YellowRealm::new(green.clone());
        let orange = OrangeRealm::new(yellow.clone());
        let red = RedRealm::new(orange.clone());

        let ratio = SpectrumRatio::new(1.5, SpectrumSide::SpaceTime);
        let spectrum_config = IndividualSpectrumConfiguration::new(ratio);

        SubSubLogos::new(
            EntityId::new(id.to_string()),
            crate::entity_layer7::layer7::EntityType::Individual,
            None,   // parent_id
            vec![], // composition
            None,   // environment_id
            violet,
            indigo,
            blue,
            green,
            yellow,
            orange,
            red,
            spectrum_config,
        )
    }

    #[test]
    fn test_environmental_interaction_manager_creation() {
        let manager = EnvironmentalInteractionManager::new();
        assert_eq!(manager.simulation_time, 0);
        assert_eq!(manager.statistics.total_interactions, 0);
    }

    #[test]
    fn test_initialize_environment() {
        let mut manager = EnvironmentalInteractionManager::new();

        let entity1 = create_test_entity("entity-1");
        let entity2 = create_test_entity("entity-2");

        let mut entities = HashMap::new();
        entities.insert(entity1.entity_id.clone(), entity1);
        entities.insert(entity2.entity_id.clone(), entity2);

        manager.initialize_environment(&entities);

        // Should have energy fields and vibrational fields
        assert!(manager.environment.energy_fields.len() > 0);
        assert!(manager.environment.vibrational_fields.len() > 0);
    }

    #[test]
    fn test_interact_with_environment() {
        let mut manager = EnvironmentalInteractionManager::new();

        let entity = create_test_entity("entity-1");
        let entity_id = entity.entity_id.clone();

        let mut entities = HashMap::new();
        entities.insert(entity_id.clone(), entity.clone());

        manager.initialize_environment(&entities);

        let effect = manager.interact_with_environment(&entity_id, &entity);

        // Should have some effect
        assert!(effect.magnitude >= 0.0);
        assert_eq!(manager.statistics.total_interactions, 1);
    }
}
