//! Observation Layer — Bridge between HoloSim simulation state and game-engine-consumable data.
//!
//! This module translates internal simulation state (archetype activations, spectrum position,
//! density, coherence) into structured observations that game engines (Bevy, Godot) can consume
//! directly without understanding HoloSim internals.
//!
//! # Architecture
//!
//! ```text
//! HoloSim Internals          Observation Layer           Game Engine
//! ┌─────────────────┐       ┌─────────────────┐       ┌─────────────────┐
//! │ ArchetypeBasis  │──────▶│ PhysicalObs     │──────▶│ Position, Mass  │
//! │ SpectrumConfig  │──────▶│ BehavioralObs   │──────▶│ Needs, Mood     │
//! │ Density         │──────▶│ EnvironmentalObs│──────▶│ Terrain, Weather│
//! │ FreeWill        │──────▶│ Events          │──────▶│ Game Events     │
//! └─────────────────┘       └─────────────────┘       └─────────────────┘
//! ```
//!
//! # Mapping Logic
//!
//! - **Archetype → Needs**: A1-A7 (Mind) → exploration; A8-A14 (Body) → hunger, rest;
//!   A15-A21 (Spirit) → social, growth; A22 (Choice) → proportional influence on all.
//! - **Spectrum → Environment**: spectrum_position maps to terrain type (quantum → cosmic).
//! - **Density → Capabilities**: Higher density entities have higher health ceilings.
//! - **Mood**: Derived from archetype interference pattern (-1.0 distressed to 1.0 harmonious).

use crate::simulation_v3::NUM_ARCHETYPES;
use std::collections::HashMap;

// ============================================================================
// Archetype range constants
// ============================================================================

/// Archetype indices for Mind (A1-A7)
const MIND_START: usize = 0;
const MIND_END: usize = 7;

/// Archetype indices for Body (A8-A14)
const BODY_START: usize = 7;
const BODY_END: usize = 14;

/// Archetype indices for Spirit (A15-A21)
const SPIRIT_START: usize = 14;
const SPIRIT_END: usize = 21;

/// Archetype index for Choice (A22)
const CHOICE_INDEX: usize = 21;

// ============================================================================
// Terrain types derived from spectrum position
// ============================================================================

/// Terrain classification based on holographic spectrum position.
/// Maps the space/time ↔ time/space continuum to game-world terrain types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TerrainType {
    /// Quantum realm — spectrum_position < 0.3, high energy, subatomic
    Quantum,
    /// Biological realm — spectrum_position 0.3–0.5, organic structures
    Biological,
    /// Planetary realm — spectrum_position 0.5–0.7, world-scale
    Planetary,
    /// Stellar realm — spectrum_position 0.7–0.9, star-scale
    Stellar,
    /// Cosmic realm — spectrum_position > 0.9, galactic/universal
    Cosmic,
}

impl std::fmt::Display for TerrainType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TerrainType::Quantum => write!(f, "quantum"),
            TerrainType::Biological => write!(f, "biological"),
            TerrainType::Planetary => write!(f, "planetary"),
            TerrainType::Stellar => write!(f, "stellar"),
            TerrainType::Cosmic => write!(f, "cosmic"),
        }
    }
}

// ============================================================================
// Event types from free will choices and state transitions
// ============================================================================

/// Types of simulation events generated by entity state changes.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum EventType {
    /// Entity changed density level
    DensityTransition { from_density: u8, to_density: u8 },
    /// Entity made a significant choice (high A22 activation)
    SignificantChoice,
    /// Entity experienced archetype interference spike
    ArchetypicalEvent,
    /// Entity entered a new terrain region
    TerrainChange { terrain: TerrainType },
    /// Entity coherence dropped critically
    CoherenceDrop,
    /// Entity coherence reached peak
    CoherencePeak,
}

impl std::fmt::Display for EventType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EventType::DensityTransition {
                from_density,
                to_density,
            } => write!(f, "DensityTransition({}→{})", from_density, to_density),
            EventType::SignificantChoice => write!(f, "SignificantChoice"),
            EventType::ArchetypicalEvent => write!(f, "ArchetypicalEvent"),
            EventType::TerrainChange { terrain } => write!(f, "TerrainChange({})", terrain),
            EventType::CoherenceDrop => write!(f, "CoherenceDrop"),
            EventType::CoherencePeak => write!(f, "CoherencePeak"),
        }
    }
}

// ============================================================================
// Observation data structures
// ============================================================================

/// Physical properties derived from archetype activation and density.
/// Game engines consume this for rendering, physics, and entity state.
#[derive(Debug, Clone)]
pub struct PhysicalObservation {
    pub entity_id: u64,
    pub position: [f64; 3],
    pub velocity: [f64; 3],
    pub mass: f64,
    pub temperature: f64,
    pub charge: f64,
    pub health: f64,
    pub energy_level: f64,
}

/// Behavioral outputs derived from archetype interference patterns.
/// Game engines consume this for AI, needs systems, and personality.
#[derive(Debug, Clone)]
pub struct BehavioralObservation {
    pub entity_id: u64,
    /// [Hunger, Social, Rest, Exploration, Growth] — each 0.0–1.0
    pub needs: [f64; 5],
    /// -1.0 (distressed) to 1.0 (harmonious), from archetype interference
    pub mood: f64,
    /// Emergent goal from free will + archetype pull
    pub current_goal: Option<String>,
    /// Direct 22-archetype activation profile
    pub personality_profile: [f64; 22],
    /// 0.0–1.0, behavioral consistency
    pub stability: f64,
    /// 0.0–1.0, behavioral novelty/unexpectedness
    pub novelty: f64,
}

/// Environmental data derived from holographic field state.
/// Game engines consume this for world generation, weather, and resources.
#[derive(Debug, Clone)]
pub struct EnvironmentalObservation {
    pub region_id: u64,
    pub terrain_type: TerrainType,
    pub weather_intensity: f64,
    pub resource_density: f64,
    pub danger_level: f64,
    pub social_density: f64,
}

/// Biological state derived from the biology pipeline.
/// Game engines consume this for organism rendering, disease simulation, ecosystem.
#[derive(Debug, Clone, Default)]
pub struct BiologyObservation {
    pub cell_count: u64,
    pub organism_count: u64,
    pub species_count: u64,
    pub molecule_count: u64,
    pub average_cell_health: f64,
    pub average_organism_health: f64,
    pub cell_divisions: u64,
    pub organism_deaths: u64,
    pub evolution_active: bool,
}

// ============================================================================
// GPU Compute observation types
// ============================================================================

/// A single pairwise connection computed on GPU/CPU.
/// Game engines consume this for relationship rendering, network visualization.
#[derive(Debug, Clone)]
pub struct GpuConnectionObservation {
    pub entity_a_id: String,
    pub entity_b_id: String,
    pub strength: f32,
    pub archetype_similarity: f32,
    pub spectrum_similarity: f32,
    pub blueprint_alignment: f32,
    pub resonance_match: f32,
    pub phase_coherence: f32,
    pub karmic_correlation: f32,
    pub connection_type: u32,
}

/// A single pairwise resonance score computed on GPU/CPU.
/// Game engines consume this for resonance visualization, collective dynamics.
#[derive(Debug, Clone)]
pub struct GpuResonanceObservation {
    pub entity_a_id: String,
    pub entity_b_id: String,
    pub resonance_score: f32,
    pub spectrum_resonance: f32,
    pub holographic_resonance: f32,
    pub polarity_resonance: f32,
    pub resonance_type: u32,
}

/// Aggregated GPU field observation for game engine consumption.
/// Contains all pairwise connection and resonance data from the compute engine.
#[derive(Debug, Clone)]
pub struct GpuFieldObservation {
    pub backend: String,
    pub num_entities: usize,
    pub num_connections: usize,
    pub num_resonance_pairs: usize,
    pub avg_connection_strength: f32,
    pub avg_resonance_score: f32,
    pub compute_time_ms: f64,
    pub connections: Vec<GpuConnectionObservation>,
    pub resonance_pairs: Vec<GpuResonanceObservation>,
}

/// A single simulation event from free will choices and catalyst processing.
#[derive(Debug, Clone)]
pub struct SimulationEvent {
    pub entity_id: u64,
    pub event_type: EventType,
    pub timestamp: u64,
    pub description: String,
    pub intensity: f64,
}

/// Unified observation for a single entity — the primary game-engine input.
#[derive(Debug, Clone)]
pub struct EntityObservation {
    pub physical: PhysicalObservation,
    pub behavioral: BehavioralObservation,
    pub environment: EnvironmentalObservation,
}

/// Statistics tracked by the ObservationLayer.
#[derive(Debug, Clone, Default)]
pub struct ObservationStatistics {
    pub total_observations: u64,
    pub total_events_generated: u64,
    pub peak_entity_count: u64,
    pub current_entity_count: u64,
    pub terrain_distribution: HashMap<String, u64>,
}

// ============================================================================
// Observation Layer — main translation engine
// ============================================================================

/// The Observation Layer produces structured observation data from simulation state.
///
/// Game engines call `observe_entity()` each tick with current simulation state,
/// then retrieve observations via `get_all_observations()` for rendering/sync.
pub struct ObservationLayer {
    observations: HashMap<u64, EntityObservation>,
    events: Vec<SimulationEvent>,
    stats: ObservationStatistics,
    current_tick: u64,
    previous_densities: HashMap<u64, u8>,
    previous_terrains: HashMap<u64, TerrainType>,
    biology: BiologyObservation,
    gpu_observation: Option<GpuFieldObservation>,
}

impl ObservationLayer {
    /// Create a new, empty ObservationLayer.
    pub fn new() -> Self {
        ObservationLayer {
            observations: HashMap::new(),
            events: Vec::new(),
            stats: ObservationStatistics::default(),
            current_tick: 0,
            previous_densities: HashMap::new(),
            previous_terrains: HashMap::new(),
            biology: BiologyObservation::default(),
            gpu_observation: None,
        }
    }

    /// Advance the internal tick counter. Call once per simulation tick.
    pub fn advance_tick(&mut self) {
        self.current_tick += 1;
    }

    /// Get the current tick number.
    pub fn current_tick(&self) -> u64 {
        self.current_tick
    }

    pub fn biology_observation(&self) -> &BiologyObservation {
        &self.biology
    }

    pub fn update_biology_stats(
        &mut self,
        cell_count: usize,
        organism_count: usize,
        species_count: usize,
        molecule_count: usize,
        avg_cell_health: f64,
        avg_organism_health: f64,
        cell_divisions: usize,
        organism_deaths: usize,
    ) {
        self.biology.cell_count = cell_count as u64;
        self.biology.organism_count = organism_count as u64;
        self.biology.species_count = species_count as u64;
        self.biology.molecule_count = molecule_count as u64;
        self.biology.average_cell_health = avg_cell_health;
        self.biology.average_organism_health = avg_organism_health;
        self.biology.cell_divisions += cell_divisions as u64;
        self.biology.organism_deaths += organism_deaths as u64;
        self.biology.evolution_active = cell_count > 0 || organism_count > 0;
    }

    // ========================================================================
    // GPU Field Observation
    // ========================================================================

    /// Compute and observe the holographic field using the GPU/CPU compute engine.
    ///
    /// Calls `compute_connections` and `compute_resonance` on the engine, converts
    /// results into game-consumable observation types, and stores them.
    ///
    /// # Arguments
    /// * `engine` — The compute engine (GPU or CPU backend)
    /// * `entities` — Entity data prepared for GPU upload
    pub fn observe_gpu_field(
        &mut self,
        engine: &crate::gpu::compute_engine::ComputeEngine,
        entities: &[crate::gpu::entity_upload::EntityGPUData],
    ) {
        use crate::gpu::connection_kernel::ConnectionWeights;
        use crate::gpu::resonance_kernel::ResonanceWeights;

        let num_entities = entities.len();
        if num_entities == 0 {
            self.gpu_observation = Some(GpuFieldObservation {
                backend: engine.backend().to_string(),
                num_entities: 0,
                num_connections: 0,
                num_resonance_pairs: 0,
                avg_connection_strength: 0.0,
                avg_resonance_score: 0.0,
                compute_time_ms: 0.0,
                connections: Vec::new(),
                resonance_pairs: Vec::new(),
            });
            return;
        }

        let start = std::time::Instant::now();

        let connections = engine.compute_connections(entities, &ConnectionWeights::default());
        let resonance = engine.compute_resonance(entities, &ResonanceWeights::default());

        let compute_time_ms = start.elapsed().as_secs_f64();

        let entity_id =
            |idx: usize| -> String { format!("0x{:08x}", entities[idx].entity_id_hash) };

        let connection_observations: Vec<GpuConnectionObservation> = connections
            .iter()
            .enumerate()
            .map(|(flat_idx, c)| {
                let row = flat_idx / num_entities;
                let col = flat_idx % num_entities;
                GpuConnectionObservation {
                    entity_a_id: entity_id(row),
                    entity_b_id: entity_id(col),
                    strength: c.strength,
                    archetype_similarity: c.archetype_similarity,
                    spectrum_similarity: c.spectrum_similarity,
                    blueprint_alignment: c.blueprint_alignment,
                    resonance_match: c.resonance_match,
                    phase_coherence: c.phase_coherence,
                    karmic_correlation: c.karmic_correlation,
                    connection_type: c.connection_type,
                }
            })
            .collect();

        let resonance_observations: Vec<GpuResonanceObservation> = resonance
            .iter()
            .enumerate()
            .map(|(flat_idx, r)| {
                let row = flat_idx / num_entities;
                let col = flat_idx % num_entities;
                GpuResonanceObservation {
                    entity_a_id: entity_id(row),
                    entity_b_id: entity_id(col),
                    resonance_score: r.resonance_score,
                    spectrum_resonance: r.spectrum_resonance,
                    holographic_resonance: r.holographic_resonance,
                    polarity_resonance: r.polarity_resonance,
                    resonance_type: r.resonance_type,
                }
            })
            .collect();

        let num_connections = connection_observations.len();
        let num_resonance_pairs = resonance_observations.len();

        let avg_connection_strength = if num_connections > 0 {
            connection_observations
                .iter()
                .map(|c| c.strength)
                .sum::<f32>()
                / num_connections as f32
        } else {
            0.0
        };

        let avg_resonance_score = if num_resonance_pairs > 0 {
            resonance_observations
                .iter()
                .map(|r| r.resonance_score)
                .sum::<f32>()
                / num_resonance_pairs as f32
        } else {
            0.0
        };

        self.gpu_observation = Some(GpuFieldObservation {
            backend: engine.backend().to_string(),
            num_entities,
            num_connections,
            num_resonance_pairs,
            avg_connection_strength,
            avg_resonance_score,
            compute_time_ms,
            connections: connection_observations,
            resonance_pairs: resonance_observations,
        });
    }

    /// Get the most recent GPU field observation, if one has been computed.
    pub fn get_gpu_observation(&self) -> Option<&GpuFieldObservation> {
        self.gpu_observation.as_ref()
    }

    // ========================================================================
    // Mapping: Archetype → Needs
    // ========================================================================

    /// Map archetype activation profile to behavioral needs.
    ///
    /// Mapping:
    /// - A1-A7 (Mind) → exploration need (curiosity from cognitive activation)
    /// - A8-A14 (Body) → hunger and rest needs (physical maintenance)
    /// - A15-A21 (Spirit) → social and growth needs
    /// - A22 (Choice) → proportional influence on all needs
    ///
    /// Formula: `need = avg(archetype_coeffs[range]) * (1.0 - satisfaction_base)`
    /// where satisfaction_base is derived from coherence (higher coherence = more satisfied).
    fn compute_needs(archetype_profile: &[f64; 22], coherence: f64) -> [f64; 5] {
        let satisfaction_base = coherence.clamp(0.0, 1.0);

        let mind_sum: f64 = archetype_profile[MIND_START..MIND_END].iter().sum();
        let mind_avg = mind_sum / (MIND_END - MIND_START) as f64;

        let hunger_sum: f64 = archetype_profile[BODY_START..11].iter().sum();
        let hunger_avg = hunger_sum / (11 - BODY_START) as f64;
        let rest_sum: f64 = archetype_profile[11..BODY_END].iter().sum();
        let rest_avg = rest_sum / (BODY_END - 11) as f64;

        let social_sum: f64 = archetype_profile[SPIRIT_START..18].iter().sum();
        let social_avg = social_sum / (18 - SPIRIT_START) as f64;
        let growth_sum: f64 = archetype_profile[18..SPIRIT_END].iter().sum();
        let growth_avg = growth_sum / (SPIRIT_END - 18) as f64;

        let choice = archetype_profile[CHOICE_INDEX].clamp(0.0, 1.0);
        let choice_influence = 1.0 + choice * 0.5;

        let mut needs = [
            (hunger_avg * (1.0 - satisfaction_base) * choice_influence).clamp(0.0, 1.0),
            (social_avg * (1.0 - satisfaction_base) * choice_influence).clamp(0.0, 1.0),
            (rest_avg * (1.0 - satisfaction_base) * choice_influence).clamp(0.0, 1.0),
            (mind_avg * (1.0 - satisfaction_base) * choice_influence).clamp(0.0, 1.0),
            (growth_avg * (1.0 - satisfaction_base) * choice_influence).clamp(0.0, 1.0),
        ];

        let sum: f64 = needs.iter().sum();
        if sum > 5.0 {
            let scale = 5.0 / sum;
            for n in &mut needs {
                *n *= scale;
            }
        }

        needs
    }

    // ========================================================================
    // Mapping: Mood calculation from archetype interference
    // ========================================================================

    /// Calculate mood from archetype interference pattern.
    ///
    /// mood = (positive_archetype_sum - negative_archetype_sum) / total_activation
    /// Range: -1.0 (distressed) to 1.0 (harmonious)
    fn compute_mood(archetype_profile: &[f64; 22]) -> f64 {
        let positive_sum: f64 = archetype_profile[SPIRIT_START..SPIRIT_END].iter().sum();

        let body_sum: f64 = archetype_profile[BODY_START..BODY_END].iter().sum();
        let body_count = (BODY_END - BODY_START) as f64;
        let body_mean = if body_count > 0.0 {
            body_sum / body_count
        } else {
            0.0
        };
        let body_variance: f64 = archetype_profile[BODY_START..BODY_END]
            .iter()
            .map(|&a| (a - body_mean).powi(2))
            .sum();

        let mind_sum: f64 = archetype_profile[MIND_START..MIND_END].iter().sum();

        let total: f64 = archetype_profile.iter().map(|&a| a.abs()).sum();
        if total < 1e-10 {
            return 0.0;
        }

        let distress_signal = if mind_sum > body_sum {
            0.0
        } else {
            body_variance / body_count
        };

        let mood = (positive_sum - distress_signal) / total;
        mood.clamp(-1.0, 1.0)
    }

    // ========================================================================
    // Mapping: Spectrum → Terrain
    // ========================================================================

    /// Map spectrum position to terrain type.
    ///
    /// spectrum_position < 0.3 → Quantum (high energy, subatomic)
    /// spectrum_position 0.3–0.5 → Biological (organic)
    /// spectrum_position 0.5–0.7 → Planetary (world-scale)
    /// spectrum_position 0.7–0.9 → Stellar (star-scale)
    /// spectrum_position > 0.9 → Cosmic (galactic/universal)
    fn spectrum_to_terrain(spectrum_position: f64) -> TerrainType {
        if spectrum_position < 0.3 {
            TerrainType::Quantum
        } else if spectrum_position < 0.5 {
            TerrainType::Biological
        } else if spectrum_position < 0.7 {
            TerrainType::Planetary
        } else if spectrum_position < 0.9 {
            TerrainType::Stellar
        } else {
            TerrainType::Cosmic
        }
    }

    // ========================================================================
    // Mapping: Density → Health capability
    // ========================================================================

    /// Calculate health from coherence and density.
    ///
    /// Higher density entities have higher health ceilings.
    /// health = coherence_metric * density_factor
    fn compute_health(coherence: f64, density: u8) -> f64 {
        let density_factor = 0.5 + (density as f64 / 8.0) * 0.5;
        (coherence.clamp(0.0, 1.0) * density_factor).clamp(0.0, 1.0)
    }

    // ========================================================================
    // Physical property derivation
    // ========================================================================

    /// Derive mass from archetype activation and density.
    /// Body archetypes (A8-A14) contribute most to physical mass.
    fn compute_mass(base_mass: f64, archetype_profile: &[f64; 22], density: u8) -> f64 {
        let body_sum: f64 = archetype_profile[BODY_START..BODY_END].iter().sum();
        let body_factor = 1.0 + body_sum / NUM_ARCHETYPES as f64;
        let density_multiplier = 1.0 + (density as f64 * 0.1);
        base_mass * body_factor * density_multiplier
    }

    /// Derive temperature from spectrum position and energy.
    /// Quantum spectrum = higher temperature, cosmic = lower.
    fn compute_temperature(spectrum_position: f64, energy: f64) -> f64 {
        let spectrum_factor = 1.0 - spectrum_position.clamp(0.0, 1.0);
        energy * (100.0 + spectrum_factor * 900.0)
    }

    /// Derive charge from body archetype coefficients.
    fn compute_charge(archetype_profile: &[f64; 22]) -> f64 {
        let first_half: f64 = archetype_profile[BODY_START..11].iter().sum();
        let second_half: f64 = archetype_profile[11..BODY_END].iter().sum();
        let total = (first_half + second_half).abs();
        if total < 1e-10 {
            return 0.0;
        }
        ((first_half - second_half) / total).clamp(-1.0, 1.0)
    }

    // ========================================================================
    // Environmental derivation
    // ========================================================================

    /// Derive weather intensity from spectrum position and entity energy.
    fn compute_weather_intensity(spectrum_position: f64, energy: f64) -> f64 {
        let weather_peak = if spectrum_position >= 0.3 && spectrum_position < 0.7 {
            1.0 - (spectrum_position - 0.5).abs() * 5.0
        } else {
            0.1
        };
        (weather_peak * energy.clamp(0.0, 1.0)).clamp(0.0, 1.0)
    }

    /// Derive resource density from spectrum position.
    /// Quantum and biological realms have higher resource density.
    fn compute_resource_density(spectrum_position: f64) -> f64 {
        if spectrum_position < 0.3 {
            0.8 + spectrum_position
        } else if spectrum_position < 0.5 {
            1.0 - (spectrum_position - 0.3) * 2.5
        } else if spectrum_position < 0.7 {
            0.5 - (spectrum_position - 0.5) * 1.5
        } else {
            0.2
        }
        .clamp(0.0, 1.0)
    }

    /// Derive danger level from spectrum position and archetype profile.
    fn compute_danger_level(spectrum_position: f64, archetype_profile: &[f64; 22]) -> f64 {
        let spectrum_danger = if spectrum_position < 0.3 {
            0.7 + (0.3 - spectrum_position)
        } else if spectrum_position < 0.5 {
            0.5
        } else {
            0.2
        };

        let body_sum: f64 = archetype_profile[BODY_START..BODY_END].iter().sum();
        let spirit_sum: f64 = archetype_profile[SPIRIT_START..SPIRIT_END].iter().sum();
        let aggression = if spirit_sum > 0.0 {
            (body_sum / spirit_sum).min(1.0) * 0.3
        } else if body_sum > 0.0 {
            0.3
        } else {
            0.0
        };

        (spectrum_danger + aggression).clamp(0.0, 1.0)
    }

    // ========================================================================
    // Main observation method
    // ========================================================================

    /// Update observation for a single entity from current simulation state.
    ///
    /// # Arguments
    /// * `entity_id` — Unique entity identifier
    /// * `archetype_profile` — 22-element archetype activation array
    /// * `spectrum_position` — Position on the space/time ↔ time/space spectrum (0.0–1.0)
    /// * `density` — Current density level (1–8)
    /// * `position` — 3D world position
    /// * `velocity` — 3D velocity vector
    /// * `mass` — Base mass from physics
    /// * `energy` — Energy level from holographic entity
    /// * `coherence` — Coherence metric (0.0–1.0)
    pub fn observe_entity(
        &mut self,
        entity_id: u64,
        archetype_profile: &[f64; 22],
        spectrum_position: f64,
        density: u8,
        position: [f64; 3],
        velocity: [f64; 3],
        mass: f64,
        energy: f64,
        coherence: f64,
    ) -> EntityObservation {
        let sp = spectrum_position.clamp(0.0, 1.0);
        let density = density.clamp(1, 8);

        let derived_mass = Self::compute_mass(mass, archetype_profile, density);
        let temperature = Self::compute_temperature(sp, energy);
        let charge = Self::compute_charge(archetype_profile);
        let health = Self::compute_health(coherence, density);

        let physical = PhysicalObservation {
            entity_id,
            position,
            velocity,
            mass: derived_mass,
            temperature,
            charge,
            health,
            energy_level: energy,
        };

        let needs = Self::compute_needs(archetype_profile, coherence);
        let mood = Self::compute_mood(archetype_profile);
        let stability = Self::compute_stability(archetype_profile);
        let novelty = 1.0 - stability;
        let current_goal = Self::derive_current_goal(archetype_profile);

        let behavioral = BehavioralObservation {
            entity_id,
            needs,
            mood,
            current_goal,
            personality_profile: *archetype_profile,
            stability,
            novelty,
        };

        let terrain = Self::spectrum_to_terrain(sp);
        let region_id = entity_id / 100;

        let environment = EnvironmentalObservation {
            region_id,
            terrain_type: terrain,
            weather_intensity: Self::compute_weather_intensity(sp, energy),
            resource_density: Self::compute_resource_density(sp),
            danger_level: Self::compute_danger_level(sp, archetype_profile),
            social_density: 0.0,
        };

        let observation = EntityObservation {
            physical,
            behavioral,
            environment,
        };

        if let Some(&prev_density) = self.previous_densities.get(&entity_id) {
            if prev_density != density {
                let event = SimulationEvent {
                    entity_id,
                    event_type: EventType::DensityTransition {
                        from_density: prev_density,
                        to_density: density,
                    },
                    timestamp: self.current_tick,
                    description: format!(
                        "Entity {} transitioned from {} to {} density",
                        entity_id, prev_density, density
                    ),
                    intensity: (density as i32 - prev_density as i32).abs() as f64 / 7.0,
                };
                self.events.push(event);
                self.stats.total_events_generated += 1;
            }
        }

        if let Some(&prev_terrain) = self.previous_terrains.get(&entity_id) {
            if prev_terrain != terrain {
                let event = SimulationEvent {
                    entity_id,
                    event_type: EventType::TerrainChange { terrain },
                    timestamp: self.current_tick,
                    description: format!("Entity {} entered {} terrain", entity_id, terrain),
                    intensity: 0.5,
                };
                self.events.push(event);
                self.stats.total_events_generated += 1;
            }
        }

        if coherence < 0.1 {
            let event = SimulationEvent {
                entity_id,
                event_type: EventType::CoherenceDrop,
                timestamp: self.current_tick,
                description: format!(
                    "Entity {} coherence dropped critically ({:.3})",
                    entity_id, coherence
                ),
                intensity: 1.0 - coherence,
            };
            self.events.push(event);
            self.stats.total_events_generated += 1;
        } else if coherence > 0.95 {
            let event = SimulationEvent {
                entity_id,
                event_type: EventType::CoherencePeak,
                timestamp: self.current_tick,
                description: format!(
                    "Entity {} reached coherence peak ({:.3})",
                    entity_id, coherence
                ),
                intensity: coherence,
            };
            self.events.push(event);
            self.stats.total_events_generated += 1;
        }

        self.previous_densities.insert(entity_id, density);
        self.previous_terrains.insert(entity_id, terrain);
        self.observations.insert(entity_id, observation.clone());

        self.stats.total_observations += 1;
        self.stats.current_entity_count = self.observations.len() as u64;
        if self.stats.current_entity_count > self.stats.peak_entity_count {
            self.stats.peak_entity_count = self.stats.current_entity_count;
        }

        let terrain_key = terrain.to_string();
        *self
            .stats
            .terrain_distribution
            .entry(terrain_key)
            .or_insert(0) += 1;

        observation
    }

    fn compute_stability(archetype_profile: &[f64; 22]) -> f64 {
        let mean: f64 = archetype_profile.iter().sum::<f64>() / NUM_ARCHETYPES as f64;
        let variance: f64 = archetype_profile
            .iter()
            .map(|&a| (a - mean).powi(2))
            .sum::<f64>()
            / NUM_ARCHETYPES as f64;
        let instability = (variance.sqrt() / 0.5).clamp(0.0, 1.0);
        1.0 - instability
    }

    fn derive_current_goal(archetype_profile: &[f64; 22]) -> Option<String> {
        let (max_idx, &max_val) = archetype_profile
            .iter()
            .enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())?;

        if max_val < 0.01 {
            return None;
        }

        let goal = match max_idx {
            0..=6 => format!("Explore cognitive domain (A{} dominant)", max_idx + 1),
            7..=13 => format!("Maintain physical well-being (A{} dominant)", max_idx + 1),
            14..=20 => format!("Seek spiritual growth (A{} dominant)", max_idx + 1),
            21 => "Exercise choice freely (A22 dominant)".to_string(),
            _ => "Unknown goal".to_string(),
        };
        Some(goal)
    }

    /// Remove observation for a departed entity.
    pub fn remove_entity(&mut self, entity_id: u64) {
        self.observations.remove(&entity_id);
        self.previous_densities.remove(&entity_id);
        self.previous_terrains.remove(&entity_id);
        self.stats.current_entity_count = self.observations.len() as u64;
    }

    /// Update the physical observation for an entity (position, velocity, mass, etc.).
    /// Returns true if the entity exists and was updated, false otherwise.
    pub fn update_physical_observation(
        &mut self,
        entity_id: u64,
        position: [f64; 3],
        velocity: [f64; 3],
        mass: f64,
        temperature: f64,
        charge: f64,
        health: f64,
        energy_level: f64,
    ) -> bool {
        if let Some(obs) = self.observations.get_mut(&entity_id) {
            obs.physical.position = position;
            obs.physical.velocity = velocity;
            obs.physical.mass = mass;
            obs.physical.temperature = temperature;
            obs.physical.charge = charge;
            obs.physical.health = health;
            obs.physical.energy_level = energy_level;
            true
        } else {
            false
        }
    }

    /// Get all current observations (for game engine sync).
    pub fn get_all_observations(&self) -> &HashMap<u64, EntityObservation> {
        &self.observations
    }

    /// Take all events generated since the last call, clearing the event buffer.
    pub fn take_events(&mut self) -> Vec<SimulationEvent> {
        std::mem::take(&mut self.events)
    }

    /// Get current observation statistics.
    pub fn statistics(&self) -> &ObservationStatistics {
        &self.stats
    }
}

impl Default for ObservationLayer {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// Unit Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: create a flat archetype profile with uniform values.
    fn flat_profile(value: f64) -> [f64; 22] {
        [value; 22]
    }

    /// Helper: create a profile where specific ranges have elevated values.
    fn archetype_profile(mind: f64, body: f64, spirit: f64, choice: f64) -> [f64; 22] {
        let mut profile = [0.0; 22];
        for i in MIND_START..MIND_END {
            profile[i] = mind;
        }
        for i in BODY_START..BODY_END {
            profile[i] = body;
        }
        for i in SPIRIT_START..SPIRIT_END {
            profile[i] = spirit;
        }
        profile[CHOICE_INDEX] = choice;
        profile
    }

    #[test]
    fn test_observe_entity_produces_physical() {
        let mut layer = ObservationLayer::new();
        let profile = archetype_profile(0.5, 0.6, 0.4, 0.3);

        let obs = layer.observe_entity(
            1,
            &profile,
            0.4,
            3,
            [1.0, 2.0, 3.0],
            [0.1, 0.2, 0.3],
            10.0,
            0.8,
            0.7,
        );

        assert_eq!(obs.physical.position, [1.0, 2.0, 3.0]);
        assert_eq!(obs.physical.velocity, [0.1, 0.2, 0.3]);
        assert!(obs.physical.mass > 0.0, "mass should be positive");
        assert!(
            obs.physical.temperature > 0.0,
            "temperature should be positive"
        );
        assert!(
            (0.0..=1.0).contains(&obs.physical.health),
            "health should be 0.0-1.0, got {}",
            obs.physical.health
        );
        assert!((obs.physical.energy_level - 0.8).abs() < 1e-10);
        assert_eq!(obs.physical.entity_id, 1);
    }

    #[test]
    fn test_archetype_to_needs_mapping() {
        let mind_heavy = archetype_profile(0.9, 0.1, 0.1, 0.1);
        let needs_mind = ObservationLayer::compute_needs(&mind_heavy, 0.5);

        let body_heavy = archetype_profile(0.1, 0.9, 0.1, 0.1);
        let needs_body = ObservationLayer::compute_needs(&body_heavy, 0.5);

        let spirit_heavy = archetype_profile(0.1, 0.1, 0.9, 0.1);
        let needs_spirit = ObservationLayer::compute_needs(&spirit_heavy, 0.5);

        assert!(
            needs_mind[3] > needs_mind[0] && needs_mind[3] > needs_mind[1],
            "Mind-heavy profile should prioritize exploration over hunger/social"
        );

        assert!(
            needs_body[0] > needs_body[3] && needs_body[2] > needs_body[3],
            "Body-heavy profile should prioritize hunger/rest over exploration"
        );

        assert!(
            needs_spirit[1] > needs_spirit[0] && needs_spirit[4] > needs_spirit[2],
            "Spirit-heavy profile should prioritize social/growth over hunger/rest"
        );

        for n in &needs_mind {
            assert!((0.0..=1.0).contains(n), "need should be 0.0-1.0, got {}", n);
        }
        for n in &needs_body {
            assert!((0.0..=1.0).contains(n), "need should be 0.0-1.0, got {}", n);
        }
        for n in &needs_spirit {
            assert!((0.0..=1.0).contains(n), "need should be 0.0-1.0, got {}", n);
        }
    }

    #[test]
    fn test_spectrum_to_terrain_mapping() {
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.0),
            TerrainType::Quantum
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.29),
            TerrainType::Quantum
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.3),
            TerrainType::Biological
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.49),
            TerrainType::Biological
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.5),
            TerrainType::Planetary
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.69),
            TerrainType::Planetary
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.7),
            TerrainType::Stellar
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.89),
            TerrainType::Stellar
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(0.9),
            TerrainType::Cosmic
        );
        assert_eq!(
            ObservationLayer::spectrum_to_terrain(1.0),
            TerrainType::Cosmic
        );
    }

    #[test]
    fn test_mood_calculation() {
        let spirit_heavy = archetype_profile(0.1, 0.1, 0.9, 0.1);
        let mood_positive = ObservationLayer::compute_mood(&spirit_heavy);
        assert!(
            mood_positive > 0.0,
            "Spirit-heavy profile should produce positive mood, got {}",
            mood_positive
        );

        let body_stress = archetype_profile(0.0, 1.0, 0.0, 0.0);
        let mood_negative = ObservationLayer::compute_mood(&body_stress);
        assert!(
            mood_negative <= 0.0,
            "Body-heavy without mind should produce neutral/negative mood, got {}",
            mood_negative
        );

        let flat = flat_profile(0.5);
        let mood_balanced = ObservationLayer::compute_mood(&flat);
        assert!(
            mood_balanced.abs() < 1.0,
            "Balanced profile should produce mood near zero, got {}",
            mood_balanced
        );

        let zero = flat_profile(0.0);
        let mood_zero = ObservationLayer::compute_mood(&zero);
        assert!(
            (mood_zero - 0.0).abs() < 1e-10,
            "Zero activation should produce neutral mood"
        );

        for profile in [spirit_heavy, body_stress, flat, zero] {
            let m = ObservationLayer::compute_mood(&profile);
            assert!(
                (-1.0..=1.0).contains(&m),
                "mood should be -1.0 to 1.0, got {}",
                m
            );
        }
    }

    #[test]
    fn test_observation_layer_full_cycle() {
        let mut layer = ObservationLayer::new();
        let profile = archetype_profile(0.5, 0.5, 0.5, 0.5);

        let obs = layer.observe_entity(
            42,
            &profile,
            0.6,
            2,
            [0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0],
            5.0,
            0.5,
            0.6,
        );
        assert_eq!(obs.physical.entity_id, 42);
        assert_eq!(layer.statistics().current_entity_count, 1);

        let all = layer.get_all_observations();
        assert!(all.contains_key(&42));

        layer.remove_entity(42);
        assert_eq!(layer.statistics().current_entity_count, 0);
        assert!(!layer.get_all_observations().contains_key(&42));

        assert_eq!(layer.statistics().peak_entity_count, 1);
        assert_eq!(layer.statistics().total_observations, 1);
    }

    #[test]
    fn test_events_generated_on_density_change() {
        let mut layer = ObservationLayer::new();
        let profile = archetype_profile(0.5, 0.5, 0.5, 0.5);

        layer.observe_entity(100, &profile, 0.5, 1, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.5);
        let events = layer.take_events();
        assert!(
            events.is_empty(),
            "First observation should not generate density transition events"
        );

        layer.observe_entity(100, &profile, 0.5, 3, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.5);
        let events = layer.take_events();
        assert!(
            !events.is_empty(),
            "Density change should generate at least one event"
        );

        let density_event = events.iter().find(|e| {
            matches!(
                e.event_type,
                EventType::DensityTransition {
                    from_density: 1,
                    to_density: 3
                }
            )
        });
        assert!(
            density_event.is_some(),
            "Should have density transition event 1→3"
        );

        if let Some(event) = density_event {
            assert_eq!(event.entity_id, 100);
            assert_eq!(event.timestamp, layer.current_tick());
            assert!((0.0..=1.0).contains(&event.intensity));
        }

        layer.observe_entity(100, &profile, 0.5, 3, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.5);
        let events = layer.take_events();
        let has_density_event = events
            .iter()
            .any(|e| matches!(e.event_type, EventType::DensityTransition { .. }));
        assert!(
            !has_density_event,
            "Same density should not generate density transition event"
        );
    }

    #[test]
    fn test_terrain_change_events() {
        let mut layer = ObservationLayer::new();
        let profile = archetype_profile(0.5, 0.5, 0.5, 0.5);

        layer.observe_entity(200, &profile, 0.2, 1, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.5);
        let _ = layer.take_events();

        layer.observe_entity(200, &profile, 0.4, 1, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.5);
        let events = layer.take_events();

        let terrain_event = events.iter().find(|e| {
            matches!(
                e.event_type,
                EventType::TerrainChange {
                    terrain: TerrainType::Biological
                }
            )
        });
        assert!(
            terrain_event.is_some(),
            "Terrain change should generate event"
        );
    }

    #[test]
    fn test_health_density_relationship() {
        let mut layer = ObservationLayer::new();
        let profile = archetype_profile(0.5, 0.5, 0.5, 0.5);
        let coherence = 0.8;

        let low_density = layer.observe_entity(
            300, &profile, 0.5, 1, [0.0; 3], [0.0; 3], 1.0, 0.5, coherence,
        );

        layer.remove_entity(300);

        let high_density = layer.observe_entity(
            301, &profile, 0.5, 7, [0.0; 3], [0.0; 3], 1.0, 0.5, coherence,
        );

        assert!(
            high_density.physical.health > low_density.physical.health,
            "7th density health ({:.3}) should exceed 1st density health ({:.3})",
            high_density.physical.health,
            low_density.physical.health
        );
    }

    #[test]
    fn test_coherence_events() {
        let mut layer = ObservationLayer::new();
        let profile = archetype_profile(0.5, 0.5, 0.5, 0.5);

        layer.observe_entity(400, &profile, 0.5, 1, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.05);
        let events = layer.take_events();
        let coherence_drop = events
            .iter()
            .find(|e| matches!(e.event_type, EventType::CoherenceDrop));
        assert!(
            coherence_drop.is_some(),
            "Low coherence should generate CoherenceDrop event"
        );

        layer.observe_entity(401, &profile, 0.5, 1, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.99);
        let events = layer.take_events();
        let coherence_peak = events
            .iter()
            .find(|e| matches!(e.event_type, EventType::CoherencePeak));
        assert!(
            coherence_peak.is_some(),
            "High coherence should generate CoherencePeak event"
        );
    }

    #[test]
    fn test_observation_statistics() {
        let mut layer = ObservationLayer::new();
        let profile = archetype_profile(0.5, 0.5, 0.5, 0.5);

        for i in 0..5 {
            layer.observe_entity(
                i,
                &profile,
                0.5,
                1,
                [i as f64, 0.0, 0.0],
                [0.0; 3],
                1.0,
                0.5,
                0.5,
            );
        }

        let stats = layer.statistics();
        assert_eq!(stats.total_observations, 5);
        assert_eq!(stats.current_entity_count, 5);
        assert_eq!(stats.peak_entity_count, 5);
    }

    #[test]
    fn test_take_events_clears_buffer() {
        let mut layer = ObservationLayer::new();
        let profile = archetype_profile(0.5, 0.5, 0.5, 0.5);

        layer.observe_entity(500, &profile, 0.5, 1, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.5);
        layer.observe_entity(500, &profile, 0.5, 3, [0.0; 3], [0.0; 3], 1.0, 0.5, 0.5);

        let events1 = layer.take_events();
        assert!(!events1.is_empty());

        let events2 = layer.take_events();
        assert!(
            events2.is_empty(),
            "take_events should clear the event buffer"
        );
    }

    #[test]
    fn test_needs_sum_normalized() {
        let extreme = archetype_profile(1.0, 1.0, 1.0, 1.0);
        let needs = ObservationLayer::compute_needs(&extreme, 0.0);
        let sum: f64 = needs.iter().sum();
        assert!(sum <= 5.0, "Needs sum should not exceed 5.0, got {}", sum);
    }

    #[test]
    fn test_default_observation_layer() {
        let layer = ObservationLayer::default();
        assert_eq!(layer.get_all_observations().len(), 0);
        assert_eq!(layer.statistics().total_observations, 0);
    }

    #[test]
    fn test_gpu_observation_initially_none() {
        let layer = ObservationLayer::new();
        assert!(
            layer.get_gpu_observation().is_none(),
            "GPU observation should be None before observe_gpu_field is called"
        );
    }

    #[test]
    fn test_gpu_connection_observation_struct() {
        let conn = GpuConnectionObservation {
            entity_a_id: "0x00000001".to_string(),
            entity_b_id: "0x00000002".to_string(),
            strength: 0.75,
            archetype_similarity: 0.8,
            spectrum_similarity: 0.6,
            blueprint_alignment: 0.5,
            resonance_match: 0.9,
            phase_coherence: 0.7,
            karmic_correlation: 0.4,
            connection_type: 1,
        };

        assert_eq!(conn.entity_a_id, "0x00000001");
        assert_eq!(conn.entity_b_id, "0x00000002");
        assert!((conn.strength - 0.75).abs() < 1e-6);
        assert_eq!(conn.connection_type, 1);
    }

    #[test]
    fn test_gpu_resonance_observation_struct() {
        let res = GpuResonanceObservation {
            entity_a_id: "0x00000001".to_string(),
            entity_b_id: "0x00000002".to_string(),
            resonance_score: 0.85,
            spectrum_resonance: 0.9,
            holographic_resonance: 0.7,
            polarity_resonance: 1.0,
            resonance_type: 3,
        };

        assert!((res.resonance_score - 0.85).abs() < 1e-6);
        assert_eq!(res.resonance_type, 3);
    }

    #[test]
    fn test_gpu_field_observation_struct_and_averages() {
        let connections = vec![
            GpuConnectionObservation {
                entity_a_id: "0x00000001".to_string(),
                entity_b_id: "0x00000001".to_string(),
                strength: 1.0,
                archetype_similarity: 1.0,
                spectrum_similarity: 1.0,
                blueprint_alignment: 1.0,
                resonance_match: 1.0,
                phase_coherence: 1.0,
                karmic_correlation: 1.0,
                connection_type: 0,
            },
            GpuConnectionObservation {
                entity_a_id: "0x00000001".to_string(),
                entity_b_id: "0x00000002".to_string(),
                strength: 0.5,
                archetype_similarity: 0.5,
                spectrum_similarity: 0.5,
                blueprint_alignment: 0.5,
                resonance_match: 0.5,
                phase_coherence: 0.5,
                karmic_correlation: 0.5,
                connection_type: 4,
            },
        ];

        let resonance_pairs = vec![
            GpuResonanceObservation {
                entity_a_id: "0x00000001".to_string(),
                entity_b_id: "0x00000001".to_string(),
                resonance_score: 1.0,
                spectrum_resonance: 1.0,
                holographic_resonance: 1.0,
                polarity_resonance: 1.0,
                resonance_type: 3,
            },
            GpuResonanceObservation {
                entity_a_id: "0x00000001".to_string(),
                entity_b_id: "0x00000002".to_string(),
                resonance_score: 0.3,
                spectrum_resonance: 0.3,
                holographic_resonance: 0.3,
                polarity_resonance: 0.3,
                resonance_type: 1,
            },
        ];

        let avg_conn_strength: f32 =
            connections.iter().map(|c| c.strength).sum::<f32>() / connections.len() as f32;
        let avg_res_score: f32 = resonance_pairs
            .iter()
            .map(|r| r.resonance_score)
            .sum::<f32>()
            / resonance_pairs.len() as f32;

        let field_obs = GpuFieldObservation {
            backend: "cpu".to_string(),
            num_entities: 2,
            num_connections: connections.len(),
            num_resonance_pairs: resonance_pairs.len(),
            avg_connection_strength: avg_conn_strength,
            avg_resonance_score: avg_res_score,
            compute_time_ms: 1.5,
            connections,
            resonance_pairs,
        };

        assert_eq!(field_obs.backend, "cpu");
        assert_eq!(field_obs.num_entities, 2);
        assert_eq!(field_obs.num_connections, 2);
        assert_eq!(field_obs.num_resonance_pairs, 2);
        assert!((field_obs.avg_connection_strength - 0.75).abs() < 1e-6);
        assert!((field_obs.avg_resonance_score - 0.65).abs() < 1e-6);
        assert!((field_obs.compute_time_ms - 1.5).abs() < 1e-6);
    }

    #[test]
    fn test_gpu_field_observation_empty() {
        let field_obs = GpuFieldObservation {
            backend: "cpu".to_string(),
            num_entities: 0,
            num_connections: 0,
            num_resonance_pairs: 0,
            avg_connection_strength: 0.0,
            avg_resonance_score: 0.0,
            compute_time_ms: 0.0,
            connections: Vec::new(),
            resonance_pairs: Vec::new(),
        };

        assert!(field_obs.connections.is_empty());
        assert!(field_obs.resonance_pairs.is_empty());
        assert_eq!(field_obs.avg_connection_strength, 0.0);
        assert_eq!(field_obs.avg_resonance_score, 0.0);
    }

    #[test]
    fn test_gpu_observation_store_and_retrieve() {
        let mut layer = ObservationLayer::new();

        let field_obs = GpuFieldObservation {
            backend: "gpu".to_string(),
            num_entities: 3,
            num_connections: 9,
            num_resonance_pairs: 9,
            avg_connection_strength: 0.6,
            avg_resonance_score: 0.7,
            compute_time_ms: 2.3,
            connections: Vec::new(),
            resonance_pairs: Vec::new(),
        };

        layer.gpu_observation = Some(field_obs);

        let retrieved = layer.get_gpu_observation();
        assert!(retrieved.is_some());
        let obs = retrieved.unwrap();
        assert_eq!(obs.backend, "gpu");
        assert_eq!(obs.num_entities, 3);
        assert_eq!(obs.num_connections, 9);
        assert_eq!(obs.num_resonance_pairs, 9);
        assert!((obs.avg_connection_strength - 0.6).abs() < 1e-6);
        assert!((obs.avg_resonance_score - 0.7).abs() < 1e-6);
    }

    #[test]
    fn test_gpu_observation_overwrite() {
        let mut layer = ObservationLayer::new();

        layer.gpu_observation = Some(GpuFieldObservation {
            backend: "cpu".to_string(),
            num_entities: 1,
            num_connections: 1,
            num_resonance_pairs: 1,
            avg_connection_strength: 0.5,
            avg_resonance_score: 0.5,
            compute_time_ms: 0.1,
            connections: Vec::new(),
            resonance_pairs: Vec::new(),
        });

        layer.gpu_observation = Some(GpuFieldObservation {
            backend: "gpu".to_string(),
            num_entities: 128,
            num_connections: 16384,
            num_resonance_pairs: 16384,
            avg_connection_strength: 0.8,
            avg_resonance_score: 0.75,
            compute_time_ms: 5.0,
            connections: Vec::new(),
            resonance_pairs: Vec::new(),
        });

        let obs = layer.get_gpu_observation().unwrap();
        assert_eq!(obs.backend, "gpu");
        assert_eq!(obs.num_entities, 128);
        assert_eq!(obs.num_connections, 16384);
    }

    #[test]
    fn test_gpu_observation_clone() {
        let conn = GpuConnectionObservation {
            entity_a_id: "0x00000001".to_string(),
            entity_b_id: "0x00000002".to_string(),
            strength: 0.75,
            archetype_similarity: 0.8,
            spectrum_similarity: 0.6,
            blueprint_alignment: 0.5,
            resonance_match: 0.9,
            phase_coherence: 0.7,
            karmic_correlation: 0.4,
            connection_type: 1,
        };

        let cloned = conn.clone();
        assert_eq!(cloned.entity_a_id, conn.entity_a_id);
        assert_eq!(cloned.strength, conn.strength);
        assert!(!std::ptr::eq(&cloned, &conn));

        let res = GpuResonanceObservation {
            entity_a_id: "0x00000001".to_string(),
            entity_b_id: "0x00000002".to_string(),
            resonance_score: 0.85,
            spectrum_resonance: 0.9,
            holographic_resonance: 0.7,
            polarity_resonance: 1.0,
            resonance_type: 3,
        };
        let cloned_res = res.clone();
        assert_eq!(cloned_res.resonance_score, res.resonance_score);
    }
}
