// Possibility Space Generation
//
// From COSMOLOGICAL-ARCHITECTURE.md:
// "Possibility space = quantum superposition constrained by entity state"
// "The set of all possible choices available to an entity"
// "Generated by Archetype 22 (The Choice)"
//
// This module implements:
// 1. Possibility space generation
// 2. Quantum superposition constrained by entity state
// 3. The set of all possible choices available to an entity

use crate::entity_layer7::layer7::EntityState;
use crate::types::Float;

/// Possibility Space
///
/// The set of all possible choices available to an entity.
///
/// From COSMOLOGICAL-ARCHITECTURE.md:
/// "Possibility space = quantum superposition constrained by entity state"
/// "Generated by Archetype 22 (The Choice)"
#[derive(Debug, Clone)]
pub struct PossibilitySpace {
    /// The set of all possible choices
    pub possibilities: Vec<Possibility>,

    /// Possibility space constraints
    pub constraints: PossibilityConstraints,

    /// Possibility space metadata
    pub metadata: PossibilityMetadata,
}

/// Possibility
///
/// A single possible choice.
#[derive(Debug, Clone)]
pub struct Possibility {
    /// Probability of this possibility (0.0 to 1.0)
    pub probability: Float,

    /// The outcome of this possibility
    pub outcome: Outcome,

    /// Constraints affecting this possibility
    pub constraints: Vec<Constraint>,

    /// Polarity bias (-1.0 to 1.0, negative = STS, positive = STO)
    pub polarity_bias: Float,
}

/// Outcome
///
/// The result of choosing a possibility.
#[derive(Debug, Clone)]
pub struct Outcome {
    /// Outcome type
    pub outcome_type: OutcomeType,

    /// Expected impact
    pub impact: Float,

    /// Consequences
    pub consequences: Vec<Consequence>,
}

/// Outcome Type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutcomeType {
    /// Service-to-Others outcome
    ServiceToOthers,

    /// Service-to-Self outcome
    ServiceToSelf,

    /// Neutral outcome
    Neutral,

    /// Mixed outcome
    Mixed,
}

/// Consequence
///
/// A consequence of an outcome.
#[derive(Debug, Clone)]
pub struct Consequence {
    /// Consequence type
    pub consequence_type: ConsequenceType,

    /// Severity (-1.0 to 1.0)
    pub severity: Float,

    /// Duration (0.0 to 1.0)
    pub duration: Float,
}

/// Consequence Type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConsequenceType {
    /// Physical consequence
    Physical,

    /// Mental consequence
    Mental,

    /// Emotional consequence
    Emotional,

    /// Spiritual consequence
    Spiritual,

    /// Karmic consequence
    Karmic,
}

/// Constraint
///
/// A constraint affecting a possibility.
#[derive(Debug, Clone)]
pub struct Constraint {
    /// Constraint type
    pub constraint_type: ConstraintType,

    /// Constraint strength (0.0 to 1.0)
    pub strength: Float,

    /// Direction of influence (-1.0 to 1.0)
    pub direction: Float,
}

/// Constraint Type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConstraintType {
    /// Physical constraint
    Physical,

    /// Mental constraint
    Mental,

    /// Emotional constraint
    Emotional,

    /// Spiritual constraint
    Spiritual,

    /// Karmic constraint
    Karmic,

    /// Environmental constraint
    Environmental,
}

/// Possibility Constraints
///
/// Constraints that apply to the entire possibility space.
#[derive(Debug, Clone)]
pub struct PossibilityConstraints {
    /// Vibrational constraint
    pub vibrational_constraint: Float,

    /// Polarity constraint
    pub polarity_constraint: Float,

    /// Consciousness constraint
    pub consciousness_constraint: Float,

    /// Karmic constraint
    pub karmic_constraint: Float,
}

/// Possibility Metadata
///
/// Metadata about the possibility space.
#[derive(Debug, Clone)]
pub struct PossibilityMetadata {
    /// Generation timestamp
    pub timestamp: u64,

    /// Entity consciousness level at generation
    pub consciousness_level: Float,

    /// Total possibility space size
    pub total_possibilities: usize,

    /// Effective possibility space size (after constraints)
    pub effective_possibilities: usize,
}

impl PossibilitySpace {
    /// Create a new possibility space from entity state
    ///
    /// From COSMOLOGICAL-ARCHITECTURE.md:
    /// "Possibility space = quantum superposition constrained by entity state"
    pub fn from_entity_state(entity_state: &EntityState) -> Self {
        // Calculate constraints
        let constraints = PossibilityConstraints::from_entity_state(entity_state);

        // Generate base possibilities (quantum superposition)
        let base_possibilities = Self::generate_quantum_superposition(entity_state);

        // Apply constraints
        let constrained_possibilities = Self::apply_constraints(base_possibilities, &constraints);

        // Apply polarity bias
        let polarized_possibilities =
            Self::apply_polarity_bias(constrained_possibilities, entity_state);

        // Create metadata
        let metadata = PossibilityMetadata {
            timestamp: 0, // TODO: Add actual timestamp
            consciousness_level: entity_state.consciousness_level,
            total_possibilities: polarized_possibilities.len(),
            effective_possibilities: polarized_possibilities.len(),
        };

        PossibilitySpace {
            possibilities: polarized_possibilities,
            constraints,
            metadata,
        }
    }

    /// Generate quantum superposition (base possibilities)
    ///
    /// This represents the quantum superposition before constraints.
    fn generate_quantum_superposition(entity_state: &EntityState) -> Vec<Possibility> {
        // Number of possibilities scales with consciousness level
        let num_possibilities = (entity_state.consciousness_level * 20.0) as usize + 10;

        (0..num_possibilities)
            .map(|i| {
                let base_probability = (i as Float + 1.0) / (num_possibilities as Float + 1.0);

                // Determine outcome type based on index
                let outcome_type = match i % 3 {
                    0 => OutcomeType::ServiceToOthers,
                    1 => OutcomeType::ServiceToSelf,
                    _ => OutcomeType::Neutral,
                };

                Possibility {
                    probability: base_probability,
                    outcome: Outcome {
                        outcome_type,
                        impact: base_probability,
                        consequences: Vec::new(),
                    },
                    constraints: Vec::new(),
                    polarity_bias: 0.0, // Will be set later
                }
            })
            .collect()
    }

    /// Apply constraints to possibilities
    fn apply_constraints(
        possibilities: Vec<Possibility>,
        constraints: &PossibilityConstraints,
    ) -> Vec<Possibility> {
        possibilities
            .into_iter()
            .map(|mut p| {
                // Apply vibrational constraint
                p.probability *= constraints.vibrational_constraint;

                // Apply polarity constraint
                p.probability *= constraints.polarity_constraint;

                // Apply consciousness constraint
                p.probability *= constraints.consciousness_constraint;

                // Apply karmic constraint
                p.probability *= constraints.karmic_constraint;

                // Ensure probability stays in valid range
                p.probability = p.probability.clamp(0.0, 1.0);

                p
            })
            .collect()
    }

    /// Apply polarity bias to possibilities
    fn apply_polarity_bias(
        possibilities: Vec<Possibility>,
        entity_state: &EntityState,
    ) -> Vec<Possibility> {
        // Polarity bias: -1.0 (STS) to 1.0 (STO)
        let polarity_bias = entity_state.polarity_state.polarity_bias;
        let sto_bias = polarity_bias.max(0.0); // STO component (0.0 to 1.0)
        let sts_bias = (-polarity_bias).max(0.0); // STS component (0.0 to 1.0)

        possibilities
            .into_iter()
            
            .map(|mut p| {
                // Apply polarity bias based on outcome type
                match p.outcome.outcome_type {
                    OutcomeType::ServiceToOthers => {
                        p.polarity_bias = sto_bias - sts_bias;
                        p.probability *= (1.0 + sto_bias * 0.3).min(1.0);
                    }
                    OutcomeType::ServiceToSelf => {
                        p.polarity_bias = sts_bias - sto_bias;
                        p.probability *= (1.0 + sts_bias * 0.3).min(1.0);
                    }
                    OutcomeType::Neutral => {
                        p.polarity_bias = 0.0;
                    }
                    OutcomeType::Mixed => {
                        p.polarity_bias = (sto_bias - sts_bias) * 0.5;
                    }
                }

                p
            })
            .collect()
    }

    /// Select a possibility (non-deterministic)
    ///
    /// Non-deterministic selection (not random, not predetermined).
    pub fn select_possibility(&self) -> Option<usize> {
        if self.possibilities.is_empty() {
            return None;
        }

        // Weighted selection based on probability
        use rand::Rng;
        let mut rng = rand::thread_rng();

        let weights: Vec<Float> = self.possibilities.iter().map(|p| p.probability).collect();
        let total: Float = weights.iter().sum();

        if total > 0.0 {
            let mut cumulative = 0.0;
            let r: Float = rng.gen::<f64>() * total;

            for (i, &weight) in weights.iter().enumerate() {
                cumulative += weight;
                if r <= cumulative {
                    return Some(i);
                }
            }
        }

        Some(self.possibilities.len() - 1)
    }

    /// Get possibility space statistics
    pub fn get_statistics(&self) -> PossibilitySpaceStatistics {
        let total_possibilities = self.possibilities.len();

        let avg_probability = if total_possibilities > 0 {
            let sum: Float = self.possibilities.iter().map(|p| p.probability).sum();
            sum / total_possibilities as Float
        } else {
            0.0
        };

        let sto_possibilities = self
            .possibilities
            .iter()
            .filter(|p| p.outcome.outcome_type == OutcomeType::ServiceToOthers)
            .count();

        let sts_possibilities = self
            .possibilities
            .iter()
            .filter(|p| p.outcome.outcome_type == OutcomeType::ServiceToSelf)
            .count();

        PossibilitySpaceStatistics {
            total_possibilities,
            effective_possibilities: self.metadata.effective_possibilities,
            avg_probability,
            sto_possibilities,
            sts_possibilities,
            consciousness_level: self.metadata.consciousness_level,
        }
    }

    /// Filter possibilities by outcome type
    pub fn filter_by_outcome_type(&self, outcome_type: OutcomeType) -> Vec<&Possibility> {
        self.possibilities
            .iter()
            .filter(|p| p.outcome.outcome_type == outcome_type)
            .collect()
    }

    /// Get top N possibilities by probability
    pub fn get_top_possibilities(&self, n: usize) -> Vec<&Possibility> {
        let mut sorted: Vec<_> = self.possibilities.iter().collect();
        sorted.sort_by(|a, b| b.probability.partial_cmp(&a.probability).unwrap());
        sorted.into_iter().take(n).collect()
    }
}

impl PossibilityConstraints {
    /// Create possibility constraints from entity state
    pub fn from_entity_state(entity_state: &EntityState) -> Self {
        PossibilityConstraints {
            vibrational_constraint: entity_state.vibrational_state.coherence,
            polarity_constraint: 1.0 - (entity_state.polarity_state.polarization_strength * 0.3),
            consciousness_constraint: (entity_state.consciousness_level * 0.5 + 0.5).min(1.0),
            karmic_constraint: 1.0 - (entity_state.experience_accumulation * 0.01).min(1.0), // Using experience_accumulation as proxy
        }
    }
}

impl Default for Outcome {
    fn default() -> Self {
        Outcome {
            outcome_type: OutcomeType::Neutral,
            impact: 0.5,
            consequences: Vec::new(),
        }
    }
}

/// Possibility Space Statistics
///
/// Statistics about the possibility space.
#[derive(Debug, Clone)]
pub struct PossibilitySpaceStatistics {
    /// Total number of possibilities
    pub total_possibilities: usize,

    /// Effective number of possibilities (after constraints)
    pub effective_possibilities: usize,

    /// Average probability
    pub avg_probability: Float,

    /// Number of STO possibilities
    pub sto_possibilities: usize,

    /// Number of STS possibilities
    pub sts_possibilities: usize,

    /// Consciousness level at generation
    pub consciousness_level: Float,
}

// ============================================================================
// UNIT TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity_layer7::layer7::{PolarityState as EntityPolarityState, VibrationalState};

    fn create_test_entity_state(consciousness_level: f64) -> EntityState {
        use crate::evolution_density_octave::density_octave::{Density, Density1SubLevel};
        EntityState {
            vibrational_state: VibrationalState {
                frequency: 0.5,
                amplitude: 0.5,
                coherence: 0.7,
                density: Density::First(Density1SubLevel::Quantum),
                potential_energy: 0.5,
                kinetic_energy: 0.5,
            },
            polarity_state: EntityPolarityState {
                polarity_bias: 0.3,
                polarization_strength: 0.5,
            },
            consciousness_level,
            experience_accumulation: 10.0,
            learning_progress: 0.5,
        }
    }

    #[test]
    fn test_possibility_space_creation() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        assert!(!possibility_space.possibilities.is_empty());
        assert!(possibility_space.possibilities.len() >= 10);
        assert_eq!(possibility_space.metadata.consciousness_level, 0.5);
    }

    #[test]
    fn test_quantum_superposition_generation() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        // Check that we have a range of outcomes
        let has_sto = possibility_space
            .possibilities
            .iter()
            .any(|p| p.outcome.outcome_type == OutcomeType::ServiceToOthers);
        let has_sts = possibility_space
            .possibilities
            .iter()
            .any(|p| p.outcome.outcome_type == OutcomeType::ServiceToSelf);
        let has_neutral = possibility_space
            .possibilities
            .iter()
            .any(|p| p.outcome.outcome_type == OutcomeType::Neutral);

        assert!(has_sto || has_sts || has_neutral);
    }

    #[test]
    fn test_constraint_application() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        // Check that constraints are applied
        assert!(possibility_space.constraints.vibrational_constraint > 0.0);
        assert!(possibility_space.constraints.polarity_constraint > 0.0);
        assert!(possibility_space.constraints.consciousness_constraint > 0.0);
    }

    #[test]
    fn test_polarity_bias_application() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        // Check that polarity bias is applied
        let has_bias = possibility_space
            .possibilities
            .iter()
            .any(|p| p.polarity_bias != 0.0);

        assert!(has_bias);
    }

    #[test]
    fn test_select_possibility() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        let selected = possibility_space.select_possibility();

        assert!(selected.is_some());
        if let Some(index) = selected {
            assert!(index < possibility_space.possibilities.len());
        }
    }

    #[test]
    fn test_non_deterministic_selection() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        // Make multiple selections and check for non-determinism
        let mut selected_indices = Vec::new();

        for _ in 0..50 {
            if let Some(index) = possibility_space.select_possibility() {
                selected_indices.push(index);
            }
        }

        // Non-deterministic means we should see variety in selections
        let unique_indices: std::collections::HashSet<_> = selected_indices.into_iter().collect();
        assert!(
            unique_indices.len() > 1,
            "Selection should be non-deterministic"
        );
    }

    #[test]
    fn test_possibility_space_statistics() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        let stats = possibility_space.get_statistics();

        assert!(stats.total_possibilities > 0);
        assert!(stats.effective_possibilities > 0);
        assert!(stats.avg_probability >= 0.0);
        assert!(stats.avg_probability <= 1.0);
        assert_eq!(stats.consciousness_level, 0.5);
    }

    #[test]
    fn test_filter_by_outcome_type() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        let sto_possibilities =
            possibility_space.filter_by_outcome_type(OutcomeType::ServiceToOthers);
        let sts_possibilities =
            possibility_space.filter_by_outcome_type(OutcomeType::ServiceToSelf);

        // Filtered results should match statistics
        assert_eq!(
            sto_possibilities.len(),
            possibility_space.get_statistics().sto_possibilities
        );
        assert_eq!(
            sts_possibilities.len(),
            possibility_space.get_statistics().sts_possibilities
        );
    }

    #[test]
    fn test_get_top_possibilities() {
        let entity_state = create_test_entity_state(0.5);
        let possibility_space = PossibilitySpace::from_entity_state(&entity_state);

        let top_5 = possibility_space.get_top_possibilities(5);

        assert!(top_5.len() <= 5);

        // Check that they are sorted by probability
        for i in 1..top_5.len() {
            assert!(top_5[i - 1].probability >= top_5[i].probability);
        }
    }

    #[test]
    fn test_consciousness_level_influence() {
        let low_consciousness_state = create_test_entity_state(0.1);
        let high_consciousness_state = create_test_entity_state(0.9);

        let low_space = PossibilitySpace::from_entity_state(&low_consciousness_state);
        let high_space = PossibilitySpace::from_entity_state(&high_consciousness_state);

        // Higher consciousness should result in more possibilities
        assert!(high_space.possibilities.len() >= low_space.possibilities.len());
    }

    #[test]
    fn test_polarity_bias_influence() {
        let mut high_sto_state = create_test_entity_state(0.5);
        high_sto_state.polarity_state.polarity_bias = 0.9;
        high_sto_state.polarity_state.polarization_strength = 0.9;

        let mut high_sts_state = create_test_entity_state(0.5);
        high_sts_state.polarity_state.polarity_bias = -0.9;
        high_sts_state.polarity_state.polarization_strength = 0.9;

        let sto_space = PossibilitySpace::from_entity_state(&high_sto_state);
        let sts_space = PossibilitySpace::from_entity_state(&high_sts_state);

        // STO bias should increase STO possibilities
        let sto_space_stats = sto_space.get_statistics();
        let sts_space_stats = sts_space.get_statistics();

        // Check that bias affects probabilities
        let sto_avg = sto_space
            .possibilities
            .iter()
            .filter(|p| p.outcome.outcome_type == OutcomeType::ServiceToOthers)
            .map(|p| p.probability)
            .sum::<Float>()
            / sto_space_stats.sto_possibilities.max(1) as Float;

        let sts_avg = sts_space
            .possibilities
            .iter()
            .filter(|p| p.outcome.outcome_type == OutcomeType::ServiceToSelf)
            .map(|p| p.probability)
            .sum::<Float>()
            / sts_space_stats.sts_possibilities.max(1) as Float;

        // High STO orientation should result in higher average STO probability
        assert!(sto_avg >= sts_avg * 0.8); // Some overlap is expected
    }
}
